### ISSUE TITLE
生成 HTML 文件时使用相对路径

### ISSUE THREAD

**Issue by lilydjwg** [CatTail/catlog#1]
因为不是所有应用场景都能够预先知道 `base_url`。生成相对路径时可以根据要生成的 HTML 文件的路径来确定需要向上跳多少目录层级。

**Comment by CatTail** [comment]
fix in [release v0.1.4](https://github.com/catlog/catlog/commit/064573fb53812278a766cc1ff8bf31556c7e9de3)
新增asset-url来共用资源
