### ISSUE TITLE
文章里不能嵌入html code吗？

### ISSUE THREAD

**Issue by luckypoem** [CatTail/catlog#5]
hi
我在文章里嵌入html code，文章发表后，并不能显示相应的效果。如何嵌入html code?
http://as3.brite.biz:24370/misc/2013/12/22/wether-shine-or-rain/index.html

**Comment by CatTail** [comment]
Duplicated #4 , fix in 4da96d89c84570ce85158d82e7ec32af2759dc00, please update by `npm update -g catlogjs`
